config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  
  resources :users do
    resources :lists, only: [:index]
  end
  

  root to: "cards#index"
  
  resources :books do
    resources :cards, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  end
  
  # resources :cards, except: [:index, :show, :new, :create] # こちらはコメントアウトまたは削除
  
  get 'chats', to: 'chats#index'
  get 'search', to: 'chats#search'

  resources :favorites, only: [:index, :create, :destroy]
  resources :watchlists, only: [:create, :destroy]
  
  resources :cards, only: [:index] do
    resource :like, only: [:create, :destroy]
  end

  resources :search_histories, only: [:index]

  resources :lists, only: [:index, :new, :create, :edit, :update, :destroy, :show]

end

app/models/aibook.rb
class Aibook
  # 属性のアクセサを定義
  attr_accessor :title, :isbn, :description, :image_url, :author, :publisher, :published_date

  # 初期化メソッドを定義
  def initialize(attrs = {})
    @title = attrs[:title]
    @isbn = attrs[:isbn]
    @description = attrs[:description]
    @image_url = attrs[:image_url] # このサンプルでは使っていませんが、参考のために追加
    @author = attrs[:author]
    @publisher = attrs[:publisher]
    @published_date = attrs[:published_date]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :cards
  has_one_attached :image
  
  def self.fetch_book_details(isbn)
    cached_data = Rails.cache.fetch("book_#{isbn}", expires_in: 12.hours) do
      # APIからのデータ取得処理
      response = HTTParty.get("https://www.googleapis.com/books/v1/volumes?q=isbn:#{isbn}")
      response.body if response.success?
    end
    JSON.parse(cached_data)
  end
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :book
  accepts_nested_attributes_for :book
  belongs_to :user

  has_many :favorites, dependent: :destroy
  has_many :users, through: :favorites

  has_many :watchlists, dependent: :destroy
  has_many :watchers, through: :watchlists, source: :user

  has_many :likes, dependent: :destroy
  has_many :likers, through: :likes, source: :user

  has_many :list_cards
  has_many :lists, through: :list_cards
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :card

  validates :user_id, uniqueness: { scope: :card_id }
end

app/models/like.rb
class Like < ApplicationRecord
  
  belongs_to :user
  belongs_to :card
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :list_cards, dependent: :destroy
  has_many :cards, through: :list_cards
end

app/models/list_card.rb
class ListCard < ApplicationRecord
  belongs_to :list
  belongs_to :card
end

app/models/search_history.rb
class SearchHistory < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true 
  validates :profile, length: { maximum: 200 } 

  has_many :cards
  mount_uploader :profile_image, ProfileImageUploader    

  def generate_sns_url
    base_url = case sns_type
      when 'Facebook' then "https://www.facebook.com/"
      when 'Twitter' then "https://twitter.com/"
      when 'Instagram' then "https://instagram.com/"
      when 'LinkedIn' then "https://www.linkedin.com/in/"
      else nil
    end

    "#{base_url}#{sns_username}" if base_url
  end

  has_many :favorites, dependent: :destroy
  # もしFavoriteモデルを介してCardモデルと関連付けているならば
  has_many :cards, through: :favorites

  has_many :watchlists, dependent: :destroy
  has_many :watched_cards, through: :watchlists, source: :card
  has_many :likes, dependent: :destroy
  has_many :search_histories, dependent: :destroy
  has_many :lists
  
  def watch(card)
    watched_cards << card unless watching?(card)
  end

  def unwatch(card)
    watched_cards.destroy(card) if watching?(card)
  end

  def watching?(card)
    watched_cards.include?(card)
  end

  def own_cards
    Card.where(user_id: id)
  end

end

app/models/watchlist.rb
class Watchlist < ApplicationRecord
  belongs_to :user
  belongs_to :card
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
  
    if @book.save
      # オブジェクトを保存した後、編集ページにリダイレクトする
      redirect_to new_book_card_path(@book)
    else
      render :new
    end
  end
  
  def index
    @books = Book.all
  end

  def edit
    @book = Book.find(params[:id])
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to books_path, notice: '書籍情報が更新されました。'
    else
      render :edit
    end
  end
  

  private

  def book_params
    params.require(:book).permit(:title, :author, :publisher, :published_date, :image_url, :isbn, :comment, :rating, :image)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_list, only: [:show, :edit, :update, :destroy]
  before_action :set_user, only: [:index, :show]
  before_action :check_user, only: [:edit, :update]

  def index
    @list_owner = User.find_by(id: params[:user_id])
    return redirect_to root_path, alert: 'User not found' unless @list_owner
  
    @lists = @list_owner.lists
    @selected_list_id = params[:list_id] || @lists.first&.id
    @selected_list_cards = List.find_by(id: @selected_list_id)&.cards || []
  end
  
  def new
    @list = current_user.lists.build
    @cards = current_user.own_cards.order(created_at: :desc)
  end
  
  def create
    @list = current_user.lists.build(list_params)
    if @list.save
      redirect_to lists_path, notice: 'List was successfully created.'
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @list.update(list_params)
      redirect_to lists_path, notice: 'List was successfully updated.'
    else
      render :edit
    end
  end
  
  def show
    @selected_list_id = params[:id]
    @lists = @user.lists
    @selected_list_cards = List.find_by(id: @selected_list_id)&.cards || []
    render :index
  end
  
  def destroy
    logger.debug "Destroy action called for list with ID: #{@list.id}"
    @list.destroy
    redirect_to lists_path, notice: 'List was successfully destroyed.'
  end
  
  private
  
  def set_list
    @list = current_user.lists.find(params[:id])
    unless @list.user == current_user
      redirect_to root_path, alert: 'Access Denied'
    end
  end
  
  def set_user
    logger.debug "Params User ID: #{params[:user_id]}"
    @user = User.find_by(id: params[:user_id]) || current_user
    logger.debug "Set User: #{@user.inspect}"
  end

  def check_user
    logger.debug "check_user called. Current User: #{current_user.inspect}, @User: #{@user.inspect}"
    unless current_user == @user
      flash[:alert] = "You are not authorized to access this page."
      redirect_to lists_path
    end
  end

  def list_params
    params.require(:list).permit(:title, card_ids: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/test_styles_helper.rb
module TestStylesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/watchlists_helper.rb
module WatchlistsHelper
end

app/views/lists/index.html.erb
<div class="mt-4">
  <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css" />
  <script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>

  <script>
    function goBack() {
      window.history.back();
    }
  </script>

  <div class="w-full py-4 shadow-md flex justify-between items-center px-4 bg-white">
    <h1 class="text-2xl font-bold mx-auto text-black"><%= @user.name %>'s Lists</h1>
  </div>
  
   <div class="flex flex-column items-start py-2 px-4 bg-white">
    <% @lists.each do |list| %>
      <%= link_to list.title, lists_path(user_id: @list_owner.id, list_id: list.id), class: "block p-2 border-b" %>
    <% end %>
  </div>

  <div class="flex justify-around py-2 bg-gray-100">
    <% if current_user == @user %>
      <%= button_to 'リスト削除', list_path(@selected_list_id), method: :delete, id: "list-delete-button", class: 'text-white bg-red-500 p-2 rounded hover:bg-red-700' if @selected_list_id.present? %>
      <script>
        document.addEventListener('DOMContentLoaded', function() {
          const listDeleteButton = document.getElementById('list-delete-button');

          if (listDeleteButton) {
            listDeleteButton.addEventListener('click', function(event) {
              if (!window.confirm('本当にこのリストを削除しますか？')) {
                event.preventDefault();
              }
            });
          }
        });
      </script>

      <%= link_to 'リスト追加', new_list_path, class: 'text-white bg-green-500 p-2 rounded hover:bg-green-700' %>
    <% end %>
    <button onclick="goBack()" class="text-white bg-blue-500 p-2 rounded hover:bg-blue-700">戻る</button> <!-- 戻るボタンをif文の外に移動 -->
  </div>
  
  <style>
    .swiper-container {
      width: 350px;
      height: 700px;
    }
    .swiper-slide {
      width: 350px;
    }
  </style>

  <div class="swiper-container mx-auto mt-10 overflow-hidden">
    <div class="swiper-wrapper">
      <% @selected_list_cards.each do |card| %>
        <div class="swiper-slide relative bg-white shadow-2xl rounded-2xl border border-gray-300 p-4">
          <!-- Card content -->
          <div class="overflow-y-auto">
            <div class="flex flex-col items-center my-4">
              <% if card.book.image.attached? %>
              <%= image_tag card.book.image, alt: "Book Cover", class: "w-[100px] h-[175px] object-cover rounded-lg mt-4" %>
              <% else %>
                <img src="<%= card.book.image_url %>" alt="Book Cover" class="w-25 h-35 object-cover rounded-lg mt-4">
              <% end %>

              <div class="text-left w-full">
                <% ['Book Name', 'Author', 'Publisher', 'Publication Date'].zip([card.book.title, card.book.author, card.book.publisher, card.book.published_date]).each do |label, value| %>
                  <div class="border-b border-black pb-1 mb-2">
                    <strong class="text-xl font-semibold text-black"><%= label %> :</strong> <%= value %>
                  </div>
                <% end %>
              </div>
            </div>
            <div class="mt-2 text-left w-full">
              <div class="border-b border-black pb-1 mb-2">
                <strong class="text-lg font-medium text-black">Favorite Point:</strong>
              </div>
              <p class="mt-2 text-gray-800 break-words"><%= card.text %></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="swiper-pagination"></div>
  </div>

  <script>
    document.addEventListener('DOMContentLoaded', function() {
      const container = document.querySelector('.swiper-container');
      if (container) {
        const swiper = new Swiper(container, {
          direction: 'horizontal',
          loop: true,
          effect: 'flip',
          slidesPerView: 1,
          pagination: {
            el: '.swiper-pagination',
            clickable: true,
          },
        });
      }
    });
  </script>
</div>

app/views/lists/new.html.erb
<%= form_with(model: @list, local: true, class: 'space-y-6') do |form| %>
  <div class="flex flex-col space-y-4">
    <div class="flex items-center space-x-4">
      <%= form.label :title, class: 'block text-lg font-semibold text-gray-700' %>
      <%= form.text_field :title, required: true, class: 'w-full px-3 py-2 border rounded shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent' %>
    </div>
  </div>

  <div class="flex flex-col space-y-4">
    <%= form.label :cards, class: 'block text-lg font-semibold text-gray-700' %>
    <% @cards.each do |card| %>
      <div class="border p-4 rounded shadow-md bg-white space-y-4">
        <div class="flex items-center space-x-4">
          <%= check_box_tag 'list[card_ids][]', card.id, false, class: 'form-checkbox h-6 w-6 text-blue-500' %>
          <div class="flex items-center space-x-4">
           <% if card.book.image.attached? %>
          <%= image_tag card.book.image, alt: "Book Cover", class: "w-[100px] h-[175px] object-cover rounded-lg mt-4" %>
          <% else %>
            <img src="<%= card.book.image_url %>" alt="Book Cover" class="w-25 h-35 object-cover rounded-lg mt-4">
          <% end %>
            <div>
              <h2 class="text-lg font-semibold mb-1"><%= card.book.title %></h2>
              <p><strong>著者:</strong> <%= card.book.author %></p>
              <p><strong>出版社:</strong> <%= card.book.publisher %></p>
              <p><strong>出版日:</strong> <%= card.book.published_date %></p>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <div class="flex justify-end mt-6">
    <%= form.submit '登録', class: 'px-6 py-2 bg-blue-500 text-white rounded hover:bg-blue-600' %>
  </div>
<% end %>