config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  
  resources :users do
    resources :lists, only: [:index]
  end
  

  root to: "cards#index"
  
  resources :books do
    resources :cards, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  end
  
  # resources :cards, except: [:index, :show, :new, :create] # こちらはコメントアウトまたは削除
  
  get 'chats', to: 'chats#index'
  get 'search', to: 'chats#search'

  resources :favorites, only: [:index, :create, :destroy]
  resources :watchlists, only: [:create, :destroy]
  
  resources :cards, only: [:index] do
    resource :like, only: [:create, :destroy]
  end

  resources :search_histories, only: [:index]

  resources :lists, only: [:index, :new, :create, :edit, :update, :destroy, :show]

end

app/models/aibook.rb
class Aibook
  # 属性のアクセサを定義
  attr_accessor :title, :isbn, :description, :image_url, :author, :publisher, :published_date

  # 初期化メソッドを定義
  def initialize(attrs = {})
    @title = attrs[:title]
    @isbn = attrs[:isbn]
    @description = attrs[:description]
    @image_url = attrs[:image_url] # このサンプルでは使っていませんが、参考のために追加
    @author = attrs[:author]
    @publisher = attrs[:publisher]
    @published_date = attrs[:published_date]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :cards
  has_one_attached :image
  
  def self.fetch_book_details(isbn)
    cached_data = Rails.cache.fetch("book_#{isbn}", expires_in: 12.hours) do
      # APIからのデータ取得処理
      response = HTTParty.get("https://www.googleapis.com/books/v1/volumes?q=isbn:#{isbn}")
      response.body if response.success?
    end
    JSON.parse(cached_data)
  end
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :book
  accepts_nested_attributes_for :book
  belongs_to :user

  has_many :favorites, dependent: :destroy
  has_many :users, through: :favorites

  has_many :watchlists, dependent: :destroy
  has_many :watchers, through: :watchlists, source: :user

  has_many :likes, dependent: :destroy
  has_many :likers, through: :likes, source: :user

  has_many :list_cards
  has_many :lists, through: :list_cards
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :card

  validates :user_id, uniqueness: { scope: :card_id }
end

app/models/like.rb
class Like < ApplicationRecord
  
  belongs_to :user
  belongs_to :card
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :list_cards, dependent: :destroy
  has_many :cards, through: :list_cards
end

app/models/list_card.rb
class ListCard < ApplicationRecord
  belongs_to :list
  belongs_to :card
end

app/models/search_history.rb
class SearchHistory < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true 
  validates :profile, length: { maximum: 200 } 

  has_many :cards
  mount_uploader :profile_image, ProfileImageUploader    

  def generate_sns_url
    base_url = case sns_type
      when 'Facebook' then "https://www.facebook.com/"
      when 'Twitter' then "https://twitter.com/"
      when 'Instagram' then "https://instagram.com/"
      when 'LinkedIn' then "https://www.linkedin.com/in/"
      else nil
    end

    "#{base_url}#{sns_username}" if base_url
  end

  has_many :favorites, dependent: :destroy
  # もしFavoriteモデルを介してCardモデルと関連付けているならば
  has_many :cards, through: :favorites

  has_many :watchlists, dependent: :destroy
  has_many :watched_cards, through: :watchlists, source: :card
  has_many :likes, dependent: :destroy
  has_many :search_histories, dependent: :destroy
  has_many :lists
  
  def watch(card)
    watched_cards << card unless watching?(card)
  end

  def unwatch(card)
    watched_cards.destroy(card) if watching?(card)
  end

  def watching?(card)
    watched_cards.include?(card)
  end

  def own_cards
    Card.where(user_id: id)
  end

end

app/models/watchlist.rb
class Watchlist < ApplicationRecord
  belongs_to :user
  belongs_to :card
end

app/controllers/chats_controller.rb
require 'httparty'
require 'cgi' # CGI.escapeを使うために追加

class ChatsController < ApplicationController
  before_action :set_token, only: :search
  before_action :text_params, only: :search

  BASE_GOOGLE_BOOKS_URL = "https://www.googleapis.com/books/v1/volumes?q="

  def index; end

  def search
    if user_signed_in?
      if @aicard
        current_user.search_histories.create(
          query: params[:text],
          title: @aicard.title,
          isbn: @aicard.isbn,
          description: @aicard.description,
          image_url: @aicard.image_url,
          author: @aicard.author,
          publisher: @aicard.publisher,
          published_date: @aicard.published_date
        )
      else
        current_user.search_histories.create(query: params[:text])
      end
    end

    @client = OpenAI::Client.new(access_token: @api_key)

    additional_info = "必ず存在するもので、上記条件にあった書籍を一冊選び、概要:は300文字以内で回答してください。「」不要。必ず書籍は書籍:、概要は概要:の後に表示するようにしてください。"
    full_query = "#{@query} #{additional_info}"

    response = @client.chat(
      parameters: {
        model: "gpt-4",
        messages: [{ role: "user", content: full_query }],
        temperature: 0
      })

    Rails.logger.info(response.inspect)

    if response["error"]
      @chats = response["error"]["message"]
    else
      content = response.dig("choices", 0, "message", "content")

      title_match = content.match(/書籍: (.*)/)
      description_match = content.match(/概要: (.+)/)   

      Rails.logger.info("Content: #{content}")
      if title_match
        title = title_match[1].strip # stripを追加して不要な空白を削除
        Rails.logger.info("Title matched: #{title}")

        encoded_title = CGI.escape(title) # URI.encodeをCGI.escapeに変更
        google_response = HTTParty.get("#{BASE_GOOGLE_BOOKS_URL}intitle:#{encoded_title}")
        Rails.logger.info("Google Books API Response: #{google_response.inspect}")

        if google_response["items"] && google_response["items"].first
          book_data = google_response["items"].first["volumeInfo"]

          description = description_match ? description_match[1][0...300] : nil

          @aicard = Aibook.new(
            isbn: book_data["industryIdentifiers"] ? book_data["industryIdentifiers"].first["identifier"] : nil,
            title: book_data["title"],
            author: book_data["authors"] ? book_data["authors"].join(", ") : nil,
            publisher: book_data["publisher"],
            published_date: book_data["publishedDate"],
            description: description,
            image_url: book_data["imageLinks"] ? book_data["imageLinks"]["thumbnail"] : nil
          )
          Rails.logger.info("@aicard: #{@aicard.inspect}")

       # @aicardが設定された場合に検索履歴を保存
       if user_signed_in?
        current_user.search_histories.create(
          query: params[:text],
          title: @aicard.title,
          isbn: @aicard.isbn,
          description: @aicard.description,
          image_url: @aicard.image_url,
          author: @aicard.author,
          publisher: @aicard.publisher,
          published_date: @aicard.published_date
        )
      end
    else
      @chats = "該当する書籍名の書籍が見つかりませんでした。"
    end
  else
    @chats = "書籍名が見つかりませんでした。"
  end
end

# @aicardがnilの場合にqueryのみを保存する。
if user_signed_in? && @aicard.nil?
  current_user.search_histories.create(query: params[:text])
end
end 

  private

  def text_params
    @query = params[:text]
  end

  def set_token
    @api_key = Rails.application.credentials.dig(:openai, :api_key)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/test_styles_helper.rb
module TestStylesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/watchlists_helper.rb
module WatchlistsHelper
end

app/views/chats/index.html.erb
<div class="min-h-screen bg-black py-6 flex flex-col justify-center sm:py-12">
  <div class="relative py-3 sm:max-w-xl sm:mx-auto">
    <div class="relative px-4 py-10 bg-white shadow-lg sm:rounded-3xl sm:p-20">
      <div class="max-w-md mx-auto">
        <h3 class="text-2xl font-semibold text-center text-black mb-4">AImode</h3>
        <div class="divide-y divide-gray-200">
          <h3 class="text-xl mt-4 text-center text-black">質問を入力してください (最大140文字)</h3>
          <%= form_with(url: search_path, method: :get, class: "mt-8 space-y-6") do |form| %>
            <div class="relative">
              <%= form.text_field :text, size: 75, maxlength: 140, placeholder: "質問を入力...", class: "w-full p-3 transition duration-200 border border-gray-300 rounded-md focus:outline-none focus:ring-blue-500 focus:border-blue-500 focus:z-10" %>
            </div>
            
            <p class="text-xs text-gray-500 mt-3 hidden">
              書籍名で検索します。<br>
              概要: (300文字以内で回答)
            </p>
            
            <%= form.hidden_field :additional_info, value: "必ず存在するもので、上記条件にあった書籍を一冊選び、概要は300文字以内で回答してください。「」不要。必ず書籍は書籍:、概要は概要:の後に表示するようにしてください。" %>
            
            <div class="mt-8">
              <%= form.submit "検索", class: "w-full px-6 py-3 text-lg text-white border-0 rounded-md bg-blue-600 focus:ring-blue-700 focus:ring focus:ring-opacity-30" %>
            </div>
          <% end %>
          
          <div class="mt-4 text-center">
            <%= link_to '検索履歴を表示', search_histories_path, class: 'text-blue-500 underline' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/chats/search.html.erb
<div class="mx-auto w-[350px] h-[700px] mt-10 relative perspective hover:flip">
  <!-- Front of the Card -->
  <div class="card-face card-front absolute inset-0 p-4 bg-white shadow-2xl rounded-2xl border border-gray-300 transition-transform duration-700">
    <!-- 表の内容 -->
    <div class="overflow-y-auto">
      <div class="flex flex-col items-center my-4">
        <% if @aicard && @aicard.image_url.present? %>
          <img src="<%= @aicard.image_url %>" alt="Book Cover" class="max-w-[200px] mb-4 rounded-lg shadow-md">
        <% else %>
          <p>画像は利用できません</p>
        <% end %>
        <div class="text-left w-full">
          <% if @aicard %>
            <div class="border-b border-black pb-1 mb-2">
              <strong class="text-xl font-semibold text-black">書籍名:</strong> <%= @aicard.title %>
            </div>
            <div class="border-b border-black pb-1 mb-2">
              <strong class="text-xl font-semibold text-black">著者:</strong> <%= @aicard.author %>
            </div>
            <div class="border-b border-black pb-1 mb-2">
              <strong class="text-xl font-semibold text-black">出版社:</strong> <%= @aicard.publisher %>
            </div>
            <div class="border-b border-black pb-1 mb-2">
              <strong class="text-xl font-semibold text-black">出版日:</strong> <%= @aicard.published_date %>
            </div>
          <% else %>
            <p>書籍情報は利用できません</p>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <!-- Back of the Card -->
  <div class="card-face card-back absolute inset-0 p-4 bg-white shadow-2xl rounded-2xl border border-gray-300 transition-transform duration-700">
    <!-- 裏の内容 -->
    <div class="overflow-y-auto">
      <h2 class="mt-6 text-center text-3xl font-extrabold text-black mb-8">書籍詳細</h2>

      <div class="text-left w-full">
        <% if @aicard %>
          <div class="border-b border-black pb-1 mb-2">
            <strong class="text-xl font-semibold text-black">質問:</strong>
            <p class="mt-2 text-gray-800"><%= @query %></p>
          </div>

          <div class="border-b border-black pb-1 mb-2">
            <strong class="text-xl font-semibold text-black">概要:</strong>
            <p class="mt-2 text-gray-800"><%= truncate(@aicard.description, length: 300) %></p>
          </div>
        <% else %>
          <p>書籍詳細は利用できません</p>
        <% end %>
      </div>
    </div>
  </div>
</div>