config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  
  resources :users do
    resources :lists, only: [:index]
  end
  

  root to: "cards#index"
  
  resources :books do
    resources :cards, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  end
  
  # resources :cards, except: [:index, :show, :new, :create] # こちらはコメントアウトまたは削除
  
  get 'chats', to: 'chats#index'
  get 'search', to: 'chats#search'

  resources :favorites, only: [:index, :create, :destroy]
  resources :watchlists, only: [:create, :destroy]
  
  resources :cards, only: [:index] do
    resource :like, only: [:create, :destroy]
  end

  resources :search_histories, only: [:index]

  resources :lists, only: [:index, :new, :create, :edit, :update, :destroy, :show]

end

app/models/aibook.rb
class Aibook
  # 属性のアクセサを定義
  attr_accessor :title, :isbn, :description, :image_url, :author, :publisher, :published_date

  # 初期化メソッドを定義
  def initialize(attrs = {})
    @title = attrs[:title]
    @isbn = attrs[:isbn]
    @description = attrs[:description]
    @image_url = attrs[:image_url] # このサンプルでは使っていませんが、参考のために追加
    @author = attrs[:author]
    @publisher = attrs[:publisher]
    @published_date = attrs[:published_date]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :cards
  has_one_attached :image
  
  def self.fetch_book_details(isbn)
    cached_data = Rails.cache.fetch("book_#{isbn}", expires_in: 12.hours) do
      # APIからのデータ取得処理
      response = HTTParty.get("https://www.googleapis.com/books/v1/volumes?q=isbn:#{isbn}")
      response.body if response.success?
    end
    JSON.parse(cached_data)
  end
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :book
  accepts_nested_attributes_for :book
  belongs_to :user

  has_many :favorites, dependent: :destroy
  has_many :users, through: :favorites

  has_many :watchlists, dependent: :destroy
  has_many :watchers, through: :watchlists, source: :user

  has_many :likes, dependent: :destroy
  has_many :likers, through: :likes, source: :user

  has_many :list_cards
  has_many :lists, through: :list_cards
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :card

  validates :user_id, uniqueness: { scope: :card_id }
end

app/models/like.rb
class Like < ApplicationRecord
  
  belongs_to :user
  belongs_to :card
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :list_cards, dependent: :destroy
  has_many :cards, through: :list_cards
end

app/models/list_card.rb
class ListCard < ApplicationRecord
  belongs_to :list
  belongs_to :card
end

app/models/search_history.rb
class SearchHistory < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true 
  validates :profile, length: { maximum: 200 } 

  has_many :cards
  mount_uploader :profile_image, ProfileImageUploader    

  def generate_sns_url
    base_url = case sns_type
      when 'Facebook' then "https://www.facebook.com/"
      when 'Twitter' then "https://twitter.com/"
      when 'Instagram' then "https://instagram.com/"
      when 'LinkedIn' then "https://www.linkedin.com/in/"
      else nil
    end

    "#{base_url}#{sns_username}" if base_url
  end

  has_many :favorites, dependent: :destroy
  # もしFavoriteモデルを介してCardモデルと関連付けているならば
  has_many :cards, through: :favorites

  has_many :watchlists, dependent: :destroy
  has_many :watched_cards, through: :watchlists, source: :card
  has_many :likes, dependent: :destroy
  has_many :search_histories, dependent: :destroy
  has_many :lists
  
  def watch(card)
    watched_cards << card unless watching?(card)
  end

  def unwatch(card)
    watched_cards.destroy(card) if watching?(card)
  end

  def watching?(card)
    watched_cards.include?(card)
  end

  def own_cards
    Card.where(user_id: id)
  end

end

app/models/watchlist.rb
class Watchlist < ApplicationRecord
  belongs_to :user
  belongs_to :card
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
  
    if @book.save
      # オブジェクトを保存した後、編集ページにリダイレクトする
      redirect_to new_book_card_path(@book)
    else
      render :new
    end
  end
  
  def index
    @books = Book.all
  end

  def edit
    @book = Book.find(params[:id])
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to books_path, notice: '書籍情報が更新されました。'
    else
      render :edit
    end
  end
  

  private

  def book_params
    params.require(:book).permit(:title, :author, :publisher, :published_date, :image_url, :isbn, :comment, :rating, :image)
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_card, only: [:show, :edit, :update, :destroy]
  before_action :set_book, only: [:new, :create, :edit]
  before_action :check_owner, only: [:edit, :update, :destroy]
  
  def index
    case params[:sort]
    when 'own'
      @cards = current_user.own_cards.order(created_at: :desc)
    when 'watch'
      @cards = Card.joins(:watchlists).where(watchlists: { user_id: current_user.id }).order(created_at: :desc)
    when 'favorite'
      @cards = Card.joins(:favorites).where(favorites: { user_id: current_user.id }).order(created_at: :desc)
    else
      @cards = Card.all.order(created_at: :desc)
    end
  
    if params[:search].present?
      @cards = @cards.joins(:book).where('books.title LIKE ? OR books.author LIKE ? OR cards.text LIKE ?', "%#{params[:search]}%", "%#{params[:search]}%", "%#{params[:search]}%")
    end
  end
  
  def new
    @card = @book.cards.build
  end

  def create
    @book = Book.find(params[:book_id]) # または別の方法で @book をセット
    @card = @book.cards.build(card_params)
    @card.user = current_user
  
    if @card.save
      redirect_to cards_path, notice: 'Card was successfully created.'
    else
      render :new
    end
  end
  
  def show
    @user = @card.user
    if @user.nil?
      redirect_to cards_path, alert: 'User does not exist.'
    else
      @sns_url = generate_sns_url(@user.sns_type, @user.sns_username) if @user.sns_type.present? && @user.sns_username.present?
      @total_likes = Like.where(card_id: @user.cards.pluck(:id)).count
    end
  end
  
  def edit
    # 編集権限チェックは before_action で行う
    puts "@book object: #{@book.inspect}" # @bookオブジェクトのデバッグ出力
    puts "Title: #{@book.title}" # title属性のデバッグ出力
    puts "Author: #{@book.author}"
  end
  
  def update
    if @card.update(card_params)
      redirect_to book_card_path(@card.book, @card), notice: 'カードが更新されました'
    else
      render :edit
    end
  end
  

  def destroy
    @card.list_cards.destroy_all
    @card.destroy
    redirect_to cards_path, notice: 'Card was successfully deleted.'
  end
  
  private
  def set_card
    @card = Card.includes(:book).find(params[:id])
  end

  def set_book
    @book = params[:book_id] ? Book.find(params[:book_id]) : @card.book
  end
  
  def check_owner
    unless current_user == @card.user
      redirect_to cards_path, alert: "編集権限がありません"
    end
  end
  def card_params
    params.require(:card).permit(:text, book_attributes: [:title, :author, :publisher, :published_date, :image_url,:image])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/test_styles_helper.rb
module TestStylesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/watchlists_helper.rb
module WatchlistsHelper
end

app/views/books/new.html.erb
<h1 class="text-2xl font-bold my-4 border-b pb-2 text-center">バーコードをスキャン</h1> 

<div class="flex justify-center my-4">
  <button type="button" onclick="location.reload();" class='py-2 px-4 bg-red-600 text-white rounded hover:bg-red-700'>やり直す</button>
</div>

<div class="flex justify-center my-4">
  <div id="scanner" style="width: 300px; height: 210px;"></div>
</div>

<h1 class="text-2xl font-bold my-4 border-b pb-2 text-center">ISBN手入力</h1> 

<div class="flex justify-center my-4">
  <input type="text" id="isbn-input" class="border p-2 rounded" placeholder="ISBNを入力">
  <button onclick="fetchBookDetailsByInput();" class='py-2 px-4 bg-blue-600 text-white rounded hover:bg-blue-700 ml-2'>検索</button>
</div>

<h1 class="text-2xl font-bold my-4 border-b pb-2 text-center">スキャンした書籍</h1>

<div class="mx-auto max-w-screen-md p-4">
  <%= form_for @book, html: { class: 'space-y-4' } do |f| %>
    <div class="flex justify-center my-4">
      <img id="book-cover" src="" alt="Book Cover" class="max-w-[200px] hidden">
    </div>

    <div class="space-y-2">
      <%= f.label :title, "書籍名", class: "block font-bold" %>
      <%= f.text_field :title, placeholder: "Title", id: "book-title-input", class: "w-full p-2 border rounded" %>
      <%= f.label :author, "著者", class: "block font-bold" %>
      <%= f.text_field :author, placeholder: "Author", id: "book-author-input", class: "w-full p-2 border rounded" %>
      <%= f.label :publisher, "出版社", class: "block font-bold" %>
      <%= f.text_field :publisher, placeholder: "Publisher", id: "book-publisher-input", class: "w-full p-2 border rounded" %>
      <%= f.label :published_date, "出版日", class: "block font-bold" %>
      <%= f.text_field :published_date, placeholder: "Published Date", id: "book-published-date-input", class: "w-full p-2 border rounded" %>
      <%= f.hidden_field :image_url, id: "book-image-url-input" %>
    </div>
    
    <div class="mt-4 flex justify-center space-x-2">
      <%= f.submit "編集画面へ", class: 'py-2 px-4 bg-green-600 text-white rounded hover:bg-green-700' %>
    </div>
  <% end %>
</div>

<script src="https://cdn.jsdelivr.net/npm/quagga@0.12.1/dist/quagga.min.js"></script>

<script>
    function setBookDetailsToForm(details) {
        document.getElementById('book-title-input').value = details.title || '';
        document.getElementById('book-author-input').value = details.authors ? details.authors.join(', ') : '';
        document.getElementById('book-publisher-input').value = details.publisher || '';
        document.getElementById('book-published-date-input').value = details.publishedDate || '';
        if (details.imageLinks && details.imageLinks.thumbnail) {
            const bookCover = document.getElementById('book-cover');
            const imageUrlInput = document.getElementById('book-image-url-input');
            bookCover.src = details.imageLinks.thumbnail;
            imageUrlInput.value = details.imageLinks.thumbnail;
            bookCover.style.display = 'block';
        }
    }

    function fetchBookDetails(isbn) {
        const API_ENDPOINT = `https://www.googleapis.com/books/v1/volumes?q=isbn:${isbn}`;
        fetch(API_ENDPOINT)
        .then(response => response.json())
        .then(data => {
            if (data.totalItems > 0) {
                const bookDetails = data.items[0].volumeInfo;
                setBookDetailsToForm(bookDetails);
            } 
        })
        .catch(error => {
            console.error('Error fetching book details:', error);
        });
    }

    // グローバルスコープにこの関数を移動
    function fetchBookDetailsByInput() {
        const isbnInput = document.getElementById('isbn-input');
        const isbn = isbnInput.value;
        if(isbn.length === 10 || isbn.length === 13) {
            fetchBookDetails(isbn);
        } else {
            alert('入力されたバーコードは有効なISBNではありません。');
        }
    }

    document.addEventListener("DOMContentLoaded", function() {
        if (document.querySelector('#scanner')) {
            Quagga.init({
                inputStream: {
                    name: "Live",
                    type: "LiveStream",
                    target: document.querySelector('#scanner'),
                    constraints: {
                        width: 640,
                        height: 480
                    }
                },
                decoder: {
                    readers: ["ean_reader"]
                }
            }, function(err) {
                if (err) {
                    console.log(err);
                    return;
                }
                Quagga.start();
            });

            Quagga.onDetected(function(result) {
                try {
                    const isbn = result.codeResult.code;
                    if(isbn.length === 10 || isbn.length === 13) {
                        fetchBookDetails(isbn);
                        Quagga.stop(); 
                    } else {
                        console.log('Scanned barcode is not a valid ISBN:', isbn);
                    }
                } catch (error) {
                    console.error('Error during detection:', error);
                }
            });
        }
    });
</script>

app/views/cards/dalete.html.erb
<h2>本当に以下のカードを削除しますか？</h2>
<div class="bg-white shadow-lg rounded-lg mb-6 p-4">
  <h3><%= @card.book.title %></h3>
  <p>投稿者: <%= @card.user ? @card.user.name : "不明" %></p>
  <p>著者: <%= @card.book.author %></p>
  <p>出版社: <%= @card.book.publisher %></p>
  <p>出版日: <%= @card.book.published_date %></p>
  <p>投稿日: <%= @card.created_at.strftime("%Y-%m-%d %H:%M:%S") %></p>

 <%= link_to 'はい', card_path(@card), method: :delete, class: 'btn btn-danger' %>
<%= link_to 'キャンセル', cards_path, class: 'btn btn-secondary' %>
</div>

app/views/cards/index.html.erb
<div class="flex flex-col md:flex-row md:justify-between items-start md:items-center mb-4 md:max-w-[390px] mx-auto">
  <h1 class="text-xl font-bold border-b pb-2">Cards</h1>
  <% if user_signed_in? %>
    <div class="text-xs md:text-sm mt-2 md:mt-0">
      <p>My favorite count: <%= current_user.favorites.count %></p>
      <p>My watch list count: <%= current_user.watchlists.count %></p>
    </div>
  <% end %>
</div>

<% if user_signed_in? %>
  <div class="md:max-w-[390px] mx-auto">
  <%= form_with url: cards_path, method: :get, local: true, class: 'flex', id: 'sort_form' do |form| %>
  <%= form.select :sort, [['Select a filter', nil], ['All', 'all'], ['My list', 'own'], ['Favorite', 'favorite'], ['Watch list', 'watch']], {}, { id: 'sort_dropdown' } %>
<% end %>
  </div>
<% end %>


<script>
document.addEventListener('DOMContentLoaded', function() {
  const dropdown = document.getElementById('sort_dropdown');
  if (dropdown) {
    dropdown.addEventListener('change', function() {
      const form = document.getElementById('sort_form');
      if (form) {
        form.submit();
      }
    });
  }
});
</script> 

<div class="mx-auto max-w-screen-md p-4">
  <% @cards.each do |card| %>
  <div class="bg-white shadow-lg rounded-lg mb-6 p-4 relative"> <!-- relativeポジションをここに追加 -->
      <div class="absolute top-2 left-2 z-20">
  <% if current_user == card.user %>
    <p><%= card.likes.count %> likes</p> <!-- 自分の投稿の場合、カウントのみ表示 -->
  <% else %>
    <% if user_signed_in? && current_user.likes.exists?(card_id: card.id) %>
      <%= button_to card_like_path(card), method: :delete, class: 'btn bg-red-300 hover:bg-red-400 p-2 m-1 w-15 h-5 flex items-center justify-center' do %>
        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" /></svg>
        <span><%= card.likes.count %></span>
      <% end %>
    <% else %>
      <%= button_to card_like_path(card), class: 'btn bg-gray-300 hover:bg-gray-400 p-2 m-1 w-15 h-5 flex items-center justify-center' do %>
        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" /></svg>
        <span></span>
      <% end %>
    <% end %>
  <% end %>
</div>

    <div class="absolute top-2 right-2 z-10 flex space-x-2">
    <% if user_signed_in? && current_user == card.user %>
        <% if !current_user.favorites.exists?(card_id: card.id) %>
     
          <%= button_to favorites_path(card_id: card.id), class: 'rounded-full p-2 m-1 bg-gray-300 hover:bg-gray-400 w-20 h-10' do %>
            My list
          <% end %>
        <% else %>
          <%= button_to favorite_path(current_user.favorites.find_by(card_id: card.id)), method: :delete, class: 'rounded-full p-2 m-1 bg-red-300 hover:bg-red-400 w-20 h-10' do %>
            Favorite
          <% end %>
        <% end %>
      <% end %>

       <% if user_signed_in? && current_user != card.user %>
        <% if current_user.watching?(card) %>
      
          <%= button_to watchlist_path(current_user.watchlists.find_by(card: card)), method: :delete, class: 'p-2 m-1 bg-yellow-300 hover:bg-yellow-400 w-20 h-10' do %>
            Watch
          <% end %>
        <% else %>
          <%= button_to watchlists_path(card_id: card.id), class: 'p-2 m-1 bg-gray-300 hover:bg-gray-400 w-20 h-10' do %>
            Other list
          <% end %>
        <% end %>
      <% end %>
    </div>
   
      <div class="flex flex-col space-y-10 pt-10">
        <div class="flex items-center space-x-4 space-y-4">
          <% if card.book.image.attached? %>
          <%= image_tag card.book.image, alt: "Book Cover", class: "w-[100px] h-[175px] object-cover rounded-lg mt-4" %>
          <% else %>
            <img src="<%= card.book.image_url %>" alt="Book Cover" class="w-25 h-35 object-cover rounded-lg mt-4">
          <% end %>

          <div>
            <h2 class="text-xl font-semibold mb-2"><%= card.book.title %></h2>
            <div class="flex items-center">
            <% if card.user %>
              <div class="flex items-center space-x-2">
                <% if card.user.profile_image? %>
                  <%= image_tag(card.user.profile_image.url, alt: "Profile Image", class: "rounded-full w-8 h-8 shadow-md") %>
                <% end %>
                <strong>投稿者:</strong>
                <p><%= card.user.name %></p>
              </div>
            <% else %>
              <p>不明</p>
            <% end %>
          </div>
            <p><strong>著者:</strong> <%= card.book.author %></p>
            <p><strong>出版社:</strong> <%= card.book.publisher %></p>
            <p><strong>出版日:</strong> <%= card.book.published_date %></p>
          </div>
        </div>
        <div>
          <p class="mt-1 text-gray-500 text-sm"><strong>投稿日:</strong> <%= card.created_at.strftime("%Y-%m-%d %H:%M:%S") %></p>
        </div>
        
        <div class="mt-2 flex space-x-2">
          <%= link_to '詳細', book_card_path(card.book, card), class: 'flex-1 px-4 py-2 bg-teal-300 text-white rounded hover:bg-teal-400 text-center' %>

          <% if current_user == card.user %>
          <%= link_to '編集', edit_book_card_path(card.book, card), class: 'flex-1 px-4 py-2 bg-blue-300 text-white rounded hover:bg-blue-400 text-center' %>
          <%= button_to '削除', [card.book, card], method: :delete, id: "delete-button", class: 'flex-1 px-4 py-2 bg-red-300 text-white rounded hover:bg-red-400 text-center' %>
          <script>
          document.addEventListener('DOMContentLoaded', function() {
          const deleteButton = document.getElementById('delete-button');

          deleteButton.addEventListener('click', function(event) {
            if (!window.confirm('本当に削除しますか？')) {
              event.preventDefault();
            }
            });
          });
          </script>

          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<script>
// ページを離れる前にスクロール位置をセッションストレージに保存
window.addEventListener('beforeunload', function () {
  sessionStorage.setItem('scrollPosition', window.scrollY.toString());
});

// ページが読み込まれたときにスクロール位置をセッションストレージから読み出し
window.addEventListener('DOMContentLoaded', (event) => {
  const savedScrollPosition = sessionStorage.getItem('scrollPosition');
  if (savedScrollPosition) {
    window.scrollTo(0, parseInt(savedScrollPosition));
  }
});
</script>

app/views/cards/show.html.erb
<div class="mx-auto w-[350px] h-[700px] mt-10 relative perspective hover:flip">

  <!-- Front of the Card -->
  <div class="card-face card-front absolute inset-0 p-4 bg-white shadow-2xl rounded-2xl border border-gray-300 transition-transform duration-700">
    <!-- 表の内容 -->
    <div class="overflow-y-auto">
      <div class="flex flex-col items-center my-4">
       <% if @card.book.image.attached? %>
          <%= image_tag @card.book.image, alt: "Book Cover", class: "w-[100px] h-[175px] object-cover rounded-lg mt-4" %>
          <% else %>
            <img src="<%= @card.book.image_url %>" alt="Book Cover" class="w-25 h-35 object-cover rounded-lg mt-4">
          <% end %>

        <div class="text-left w-full">
          <div class="border-b border-black pb-1 mb-2">
            <strong class="text-xl font-semibold text-black">書籍名:</strong> <%= @card.book.title %>
          </div>
          <div class="border-b border-black pb-1 mb-2">
            <strong class="text-xl font-semibold text-black">著者:</strong> <%= @card.book.author %>
          </div>
          <div class="border-b border-black pb-1 mb-2">
            <strong class="text-xl font-semibold text-black">出版社:</strong> <%= @card.book.publisher %>
          </div>
          <div class="border-b border-black pb-1 mb-2">
            <strong class="text-xl font-semibold text-black">出版日:</strong> <%= @card.book.published_date %>
          </div>
        </div>
      </div>
      <div class="mt-2 text-left w-full">
        <div class="border-b border-black pb-1 mb-2">
          <strong class="text-lg font-medium text-black">推しポイント:</strong>
        </div>
        <p class="mt-2 text-gray-800 break-words"><%= @card.text %></p>
      </div>
    </div>
  </div>

  <!-- Back of the Card -->
  <div class="card-face card-back absolute inset-0 p-4 bg-white shadow-2xl rounded-2xl border border-gray-300 transition-transform duration-700">
    <!-- 裏の内容 -->
    <div class="overflow-y-auto">
      <% if @user %>
    <h2 class="mt-6 text-center text-3xl font-extrabold text-black mb-8"><%= @user.name %>'s Profile</h2>
    <%# ... other user-related information ... %>
  <% else %>
    <h2 class="mt-6 text-center text-3xl font-extrabold text-black mb-8">User does not exist.</h2>
  <% end %>

      <% if @user.errors.any? %>
        <div class="border border-red-500 p-4 rounded mb-4 bg-red-50">
          <ul class="list-disc pl-5 text-red-600">
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="flex items-center justify-center mb-4">
          <% if @user.profile_image? %>
            <div class="text-center">
              <%= image_tag(@user.profile_image.url, alt: "Profile Image", class: "rounded-full w-24 h-24 shadow-md") %>
            </div>
          <% end %>
          <div class="ml-4 bg-red-300 hover:bg-red-400 p-2 rounded flex items-center justify-center" style="min-width: 80px;">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" />
            </svg>
            <span class="ml-2"><%= @total_likes %></span>
          </div>
        </div>

        <div class="text-left w-full">
          <div class="border-b border-black pb-1 mb-2">
            <strong class="text-xl font-semibold text-black">Profile:</strong>
            <p class="mt-2 text-gray-800"><%= @user.profile %></p>
          </div>

          <!-- SNS Link -->
      <% if @sns_url %>
        <div class="border-b border-black pb-1 mb-2">
          <strong class="text-xl font-semibold text-black">SNS:</strong>
          <p class="mt-2 text-blue-600 hover:underline">
            <%= link_to @sns_url, @sns_url, target: "_blank" %>
          </p>
        </div>
      <% end %>

      <!-- MyFavoriteList Link -->
        <div class="mt-4">
        <strong class="text-xl font-semibold text-black"><%= @user.name %>'s Favorite</strong>
        <p class="mt-2">
          <%= link_to 'View Favorites', favorites_path(user_id: @user.id), class: 'text-blue-600 hover:underline' %>
        </p>
      </div>

      </div>
    </div>
  </div>

</div>
</div>

<div class="mt-4 text-center flex justify-center space-x-2">
  <%= link_to '戻る', book_cards_path(@card.book), class: 'py-2 px-4 bg-blue-500 text-white rounded hover:bg-blue-700' %>
  
  <!-- 隠しテキストフィールド (URLが入力される) -->
<input type="text" value="<%= book_card_url(@card.book, @card) %>" id="copyURL" style="position: absolute; left: -9999px;">
  <!-- コピーするボタン -->
  <button onclick="copyURLToClipboard()" class="py-2 px-4 bg-yellow-500 text-white rounded hover:bg-yellow-700">URLをコピー</button>
</div>

<script>
  function copyURLToClipboard() {
    const copyText = document.getElementById("copyURL");
    copyText.select();
    document.execCommand("copy");
    alert("URLがクリップボードにコピーされました");
  }
</script>