config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  
  resources :users do
    resources :lists, only: [:index]
  end
  

  root to: "cards#index"
  
  resources :books do
    resources :cards, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  end
  
  # resources :cards, except: [:index, :show, :new, :create] # こちらはコメントアウトまたは削除
  
  get 'chats', to: 'chats#index'
  get 'search', to: 'chats#search'

  resources :favorites, only: [:index, :create, :destroy]
  resources :watchlists, only: [:create, :destroy]
  
  resources :cards, only: [:index] do
    resource :like, only: [:create, :destroy]
  end

  resources :search_histories, only: [:index]

  resources :lists, only: [:index, :new, :create, :edit, :update, :destroy, :show]

end

app/models/aibook.rb
class Aibook
  # 属性のアクセサを定義
  attr_accessor :title, :isbn, :description, :image_url, :author, :publisher, :published_date

  # 初期化メソッドを定義
  def initialize(attrs = {})
    @title = attrs[:title]
    @isbn = attrs[:isbn]
    @description = attrs[:description]
    @image_url = attrs[:image_url] # このサンプルでは使っていませんが、参考のために追加
    @author = attrs[:author]
    @publisher = attrs[:publisher]
    @published_date = attrs[:published_date]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :cards
  has_one_attached :image
  
  def self.fetch_book_details(isbn)
    cached_data = Rails.cache.fetch("book_#{isbn}", expires_in: 12.hours) do
      # APIからのデータ取得処理
      response = HTTParty.get("https://www.googleapis.com/books/v1/volumes?q=isbn:#{isbn}")
      response.body if response.success?
    end
    JSON.parse(cached_data)
  end
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :book
  accepts_nested_attributes_for :book
  belongs_to :user

  has_many :favorites, dependent: :destroy
  has_many :users, through: :favorites

  has_many :watchlists, dependent: :destroy
  has_many :watchers, through: :watchlists, source: :user

  has_many :likes, dependent: :destroy
  has_many :likers, through: :likes, source: :user

  has_many :list_cards
  has_many :lists, through: :list_cards
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :card

  validates :user_id, uniqueness: { scope: :card_id }
end

app/models/like.rb
class Like < ApplicationRecord
  
  belongs_to :user
  belongs_to :card
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :list_cards, dependent: :destroy
  has_many :cards, through: :list_cards
end

app/models/list_card.rb
class ListCard < ApplicationRecord
  belongs_to :list
  belongs_to :card
end

app/models/search_history.rb
class SearchHistory < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true 
  validates :profile, length: { maximum: 200 } 

  has_many :cards
  mount_uploader :profile_image, ProfileImageUploader    

  def generate_sns_url
    base_url = case sns_type
      when 'Facebook' then "https://www.facebook.com/"
      when 'Twitter' then "https://twitter.com/"
      when 'Instagram' then "https://instagram.com/"
      when 'LinkedIn' then "https://www.linkedin.com/in/"
      else nil
    end

    "#{base_url}#{sns_username}" if base_url
  end

  has_many :favorites, dependent: :destroy
  # もしFavoriteモデルを介してCardモデルと関連付けているならば
  has_many :cards, through: :favorites

  has_many :watchlists, dependent: :destroy
  has_many :watched_cards, through: :watchlists, source: :card
  has_many :likes, dependent: :destroy
  has_many :search_histories, dependent: :destroy
  has_many :lists
  
  def watch(card)
    watched_cards << card unless watching?(card)
  end

  def unwatch(card)
    watched_cards.destroy(card) if watching?(card)
  end

  def watching?(card)
    watched_cards.include?(card)
  end

  def own_cards
    Card.where(user_id: id)
  end

end

app/models/watchlist.rb
class Watchlist < ApplicationRecord
  belongs_to :user
  belongs_to :card
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/watchlists_helper.rb
module WatchlistsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Oshibon</title>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%# <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %> 
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" crossorigin="anonymous">
    
  </head>

  <body>
  <div class="navbar bg-base-100 px-2 py-1 flex justify-between items-center">
  <%= link_to 'OshiBon', chats_path, class: "btn btn-ghost normal-case text-2xl font-bold ml-2" %>

  <div class="flex items-center gap-1">
    <div class="flex-none gap-1 mx-1">
      <%= form_with url: cards_path, method: :get, class: "form-control", local: true do %>
        <%= text_field_tag :search, params[:search], placeholder: "Search", class: "input input-bordered w-20 bg-white text-xs" %>
        <%# <%= submit_tag "Search", class: "btn btn-primary text-xs hidden md:inline-block ml-1" %> 
        <%= submit_tag "Search", class: "hidden" %>
      <% end %>
    </div>

    <%= link_to 'Post', new_book_path, class: 'btn btn-ghost text-xs' %>
    <%= link_to 'List', cards_path, class: 'btn btn-ghost text-xs' %>
    
    <div class="dropdown dropdown-end">
  <label tabindex="0" class="btn btn-ghost btn-circle avatar">
    <div class="w-6 rounded-full">
      <% if current_user && current_user.profile_image.present? %>
        <%= image_tag(current_user.profile_image.url, alt: "Profile Image", class: "rounded-full w-6 h-6") %>
      <% else %>
        <%= image_tag("/images/stock/photo-1534528741775-53994a69daeb.jpg", alt: "Default Profile Image", class: "rounded-full w-6 h-6") %>
      <% end %>
    </div>
  </label>
  <ul tabindex="0" class="mt-2 z-[1] p-1 shadow menu menu-sm dropdown-content bg-base-100 rounded-box w-44">
    <% if current_user %>
      <li class="text-xs">
        <%= link_to user_path(current_user), class: "justify-between" do %>
          Profile
          <span class="badge">New</span>
        <% end %>
      </li>
      <li class="text-xs">
        <%= link_to "Setting", edit_user_registration_path %>
      </li>
      <li class="text-xs">
        <%= form_with url: destroy_user_session_path, method: :delete do %>
          <%= submit_tag "Logout" %>
        <% end %>
      </li>
    <% else %>
      <li class="text-xs">
        <%= link_to "Log in", new_user_session_path %>
      </li>
    <% end %>
  </ul>
</div>


        </li>
      </ul>
    </div>
  </div>
</div>

          
    <%= yield %>

    <!-- Footer Section -->
        <footer class="footer footer-center p-4 text-base-content">
          <aside>
            <p>Copyright © 2023 - All right reserved by Oshibon Industries Ltd</p>
          </aside>
        </footer>
 
<button id="scrollTopBtn" class="fixed bottom-8 right-8 bg-red-300 text-white p-2 rounded-full transition-opacity duration-500 ease-in-out shadow-lg" style="display: none; opacity: 0;" onclick="scrollToTop()">↑</button>

<script>
  let scrollTopBtn = document.getElementById("scrollTopBtn");

  window.onscroll = function() { scrollFunction() };

  function scrollFunction() {
    if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
      scrollTopBtn.style.display = "block";
      setTimeout(function() { scrollTopBtn.style.opacity = "1"; }, 50);
    } else {
      scrollTopBtn.style.opacity = "0";
      setTimeout(function() { scrollTopBtn.style.display = "none"; }, 500); // 500 is the duration of the transition in milliseconds
    }
  }

  function scrollToTop() {
    document.body.scrollTop = 0; // For Safari
    document.documentElement.scrollTop = 0; // For Chrome, Firefox, IE and Opera
  }
</script>
 
  </body>
</html>